// Package prompt provides customizable prompt templates for AI interactions.
package prompt

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Template defines a prompt template with a name and content.
type Template struct {
	Name    string
	Content string
}

// CommentFooterTemplate is the footer added to AI review comments.
const CommentFooterTemplate = `
---
*This review was generated by [M.O.R.I.B.I.T.O.](https://github.com/pirakansa/moribito) powered by OpenCode.*`

// LoadTemplateFromFile reads a template file and returns a Template.
func LoadTemplateFromFile(path string) (Template, error) {
	trimmed := strings.TrimSpace(path)
	if trimmed == "" {
		return Template{}, fmt.Errorf("template path is empty")
	}

	data, err := os.ReadFile(trimmed)
	if err != nil {
		return Template{}, fmt.Errorf("read template %s: %w", trimmed, err)
	}

	name := filepath.Base(trimmed)
	content := strings.TrimSpace(string(data))
	if content == "" {
		return Template{}, fmt.Errorf("template %s is empty", trimmed)
	}

	return Template{Name: name, Content: content}, nil
}
