// Package prompt provides customizable prompt templates for AI interactions.
// Templates can be customized for different review styles, languages, and requirements.
package prompt

// Template defines a prompt template with a name and content.
type Template struct {
	Name        string
	Description string
	Content     string
}

// Default templates for various AI interactions.
var (
	// DefaultPRReviewTemplate is the standard template for pull request reviews.
	DefaultPRReviewTemplate = Template{
		Name:        "pr-review",
		Description: "Standard pull request code review",
		Content: `Please review the following pull request.

## Pull Request Information
- **Title**: {{.Title}}
- **Base Branch**: {{.Base}}
- **Head Branch**: {{.Head}}
- **URL**: {{.URL}}

## Description
{{.Body}}

## Changes (Diff)
` + "```diff\n{{.Diff}}\n```" + `

## Review Instructions
Please provide a code review focusing on:
1. Code quality and best practices
2. Potential bugs or issues
3. Security concerns
4. Performance implications
5. Suggestions for improvement

Keep your review concise and actionable. Use markdown formatting for clarity.`,
	}

	// ConcisePRReviewTemplate provides a shorter, focused review.
	ConcisePRReviewTemplate = Template{
		Name:        "pr-review-concise",
		Description: "Concise pull request review focusing on critical issues",
		Content: `Review this PR briefly. Focus only on:
- Critical bugs or security issues
- Breaking changes

Title: {{.Title}}
Base: {{.Base}} ← Head: {{.Head}}
` + "```diff\n{{.Diff}}\n```" + `

Reply with "LGTM" if no issues found, or list only critical concerns.`,
	}

	// JapanesePRReviewTemplate provides review output in Japanese.
	JapanesePRReviewTemplate = Template{
		Name:        "pr-review-ja",
		Description: "Pull request review in Japanese",
		Content: `以下のプルリクエストをレビューしてください。

## プルリクエスト情報
- **タイトル**: {{.Title}}
- **ベースブランチ**: {{.Base}}
- **ヘッドブランチ**: {{.Head}}

## 説明
{{.Body}}

## 変更内容 (Diff)
` + "```diff\n{{.Diff}}\n```" + `

## レビュー指示
以下の観点でコードレビューを行ってください：
1. コード品質とベストプラクティス
2. バグや問題の可能性
3. セキュリティ上の懸念
4. パフォーマンスへの影響
5. 改善提案

簡潔で実用的なレビューを日本語で提供してください。`,
	}

	// SecurityFocusedTemplate emphasizes security review.
	SecurityFocusedTemplate = Template{
		Name:        "pr-review-security",
		Description: "Security-focused pull request review",
		Content: `Perform a security-focused review of this pull request.

## PR: {{.Title}}
Branch: {{.Head}} → {{.Base}}

## Changes
` + "```diff\n{{.Diff}}\n```" + `

## Security Review Checklist
Focus exclusively on:
1. Input validation and sanitization
2. Authentication/authorization issues
3. Injection vulnerabilities (SQL, XSS, command injection)
4. Sensitive data exposure
5. Cryptographic weaknesses
6. Dependency vulnerabilities
7. Access control issues

If no security issues found, state "No security concerns identified."
Otherwise, list each issue with severity (Critical/High/Medium/Low).`,
	}
)

// CommentFooterTemplate is the footer added to AI review comments.
const CommentFooterTemplate = `
---
*This review was generated by [M.O.R.I.B.I.T.O.](https://github.com/pirakansa/moribito) powered by OpenCode.*`

// BuiltinTemplates returns all built-in templates.
func BuiltinTemplates() []Template {
	return []Template{
		DefaultPRReviewTemplate,
		ConcisePRReviewTemplate,
		JapanesePRReviewTemplate,
		SecurityFocusedTemplate,
	}
}

// GetTemplateByName returns a template by its name.
// Returns the default template if not found.
func GetTemplateByName(name string) Template {
	for _, t := range BuiltinTemplates() {
		if t.Name == name {
			return t
		}
	}
	return DefaultPRReviewTemplate
}
